import {
  FaHome,
  FaRegLightbulb,
  FaShoppingCart,
  FaGamepad,
  FaBusAlt,
  FaRegUser,
  FaStethoscope,
  FaBook,
  FaPiggyBank,
  FaUsers,
  FaFirstAid,
  FaPlaneDeparture,
  FaBriefcase,
  FaMoneyBillWave,
  FaRegBuilding,
  FaGift,
  FaChartLine,
  FaThLarge,
  FaFileInvoiceDollar,
} from "react-icons/fa";

const icons = {
  rent: FaHome,
  utilities: FaRegLightbulb,
  groceries: FaShoppingCart,
  entertainment: FaGamepad,
  transportation: FaBusAlt,
  personal: FaRegUser,
  healthcare: FaStethoscope,
  education: FaBook,
  savings: FaPiggyBank,
  family: FaUsers,
  emergency: FaFirstAid,
  vacation: FaPlaneDeparture,
  freelance: FaBriefcase,
  salary: FaMoneyBillWave,
  business: FaRegBuilding,
  gifts: FaGift,
  rental: FaHome,
  investment: FaChartLine,
  debt: FaFileInvoiceDollar,
  other: FaThLarge,
};

export default icons;
